### ISSUE TITLE
Package name dropdown does not include variant suffixes

### ISSUE THREAD

**Issue by JakeWharton** [IDEScout/SQLScout-Beta#1]
Our debug build suffixes its package name.
```groovy
android {
  buildTypes {
    debug {
      applicationIdSuffix '.debug'
    }
  }
}
```
which should yield `com.our.package.debug` in the list.

The package list is presumably pulling from manifest files. These include a bunch of library modules that are not applications and therefore should not be in the list.

You also need to take into account per-flavor package names.
```groovy
android {
  buildTypes {
    debug {
      applicationIdSuffix '.debug'
    }
  }

  productFlavors {
    free {
      applicationId 'com.example.free'
    }
    paid {
      applicationId 'com.example.paid'
    }
  }
}
```
Which should yield `com.example.free.debug` and `com.example.paid.debug` in the list.

If you use the Gradle model to query the variants for debuggable packages you should be able to build a list that is both accurate and comprehensive.

**Comment by yvonneprice** [comment]
Thank you, Jake! We are looking into this issue. We will let you know as soon as it is solved. We apologize for the inconvenience.

**Comment by yvonneprice** [comment]
Thank you, Jake, for not only filing the ticket but also suggesting the fix. I followed your advice and the bug seems to be fixed. I'll send you an email with more details.
