### ISSUE TITLE
Attempt to parse blobs

### ISSUE THREAD

**Issue by mattprecious** [IDEScout/SQLScout-Beta#3]
Columns of type `BLOB` only show values as `(BLOB)`, even if the value is an int or a string. Would be great if you recognized these values and displayed them.

**Comment by yvonneprice** [comment]
Thanks, Matt. We were thinking about including a more comprehensive BLOB viewer (including images) after we release 1.0. I'll try to squeeze a simpler parser (for Strings and ints) before 1.0.

**Comment by yvonneprice** [comment]
Now the "SQLite Console" can distinguish between binary files and text, for BLOBs. I attempted to implement the "binary file viewer" but it will take longer that I expected.
The fix has 2 parts:
1. The table displays text in BLOBs as String
2. There is a new edit action for BLOBS: "Set Text", which opens the "Edit Database Value" dialog.
![screen shot 2015-06-25 at 10 08 53 pm](https://cloud.githubusercontent.com/assets/12887606/8370986/2f88ff8e-1b85-11e5-928e-44a9f3f731a7.png)
![screen shot 2015-06-25 at 10 09 06 pm](https://cloud.githubusercontent.com/assets/12887606/8370987/2f8ac26a-1b85-11e5-8b7a-93c297fa27c7.png)
![screen shot 2015-06-25 at 10 09 36 pm](https://cloud.githubusercontent.com/assets/12887606/8370988/2f8d0caa-1b85-11e5-82d0-1a681bfdf19b.png)



(see attached images)

**Comment by mattprecious** [comment]
Works great. Thanks!

**Comment by yvonneprice** [comment]
Thank you Matt, for filing the ticket and help us improve SQLScout!
